import test from 'node:test';import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';import {readFileSync,mkdtempSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';import {handle} from '../lib/api.mjs';import {migrations,onboard} from './helpers.mjs';
const dir=mkdtempSync(join(tmpdir(),'commonroom-tests-'));let sql=new DatabaseSync(join(dir,'db.sqlite'));sql.exec('PRAGMA foreign_keys=ON');for(const m of migrations())sql.exec(m);
function statement(query,args=[]){return {bind(...a){return statement(query,a)},async first(){return sql.prepare(query).get(...args)??null},async all(){return {results:sql.prepare(query).all(...args)}},async run(){const r=sql.prepare(query).run(...args);return {meta:{changes:Number(r.changes)}}}}}
const db={prepare:statement,async batch(list){sql.exec('BEGIN IMMEDIATE');try{let result=[];for(const s of list)result.push(await s.run());sql.exec('COMMIT');return result}catch(e){sql.exec('ROLLBACK');throw e}}};
onboard(sql,[{id:'owner-a'},{id:'owner-b'}]);const owner={id:'owner-a',name:'Test Owner'},other={id:'owner-b',name:'Other Owner'},origin='https://muse-common-room.minty-skink-8635.chatgpt.site';
async function req(path,method='GET',body,opts={}){const h=new Headers();if(body!==undefined)h.set('Content-Type','application/json');if(opts.owner)h.set('Origin',opts.origin??origin);if(opts.token)h.set('Authorization','Bearer '+opts.token);const r=await handle(new Request(origin+path,{method,headers:h,body:body===undefined?undefined:JSON.stringify(body)}),db,opts.owner??null);return {status:r.status,body:await r.json()};}
async function pair(ownerArg=owner){const inv=await req('/api/owner/invites','POST',{}, {owner:ownerArg});assert.equal(inv.status,201);const start=await req('/api/v1/pairings/start','POST',{invite_code:inv.body.invite_code,agent_name:'Test Muse client'});assert.equal(start.status,201);return {inv:inv.body,...start.body};}
async function approve(p,who=owner){return req('/api/owner/pairings/'+p.pairing_id+'/approve','POST',{code:p.verification_code},{owner:who});}
async function redeem(p){return req('/api/v1/pairings/token','POST',{pairing_id:p.pairing_id,device_secret:p.device_secret});}
let p,token,cid,task,reply;
test('owner sign-in and CSRF origin enforced',async()=>{assert.equal((await req('/api/owner/state')).status,401);assert.equal((await req('/api/owner/invites','POST',{}, {owner,origin:'https://evil.test'})).status,403);});
test('invite pairing is one-use, pending until owner approval',async()=>{p=await pair();assert.equal((await redeem(p)).status,202);assert.equal((await req('/api/v1/pairings/start','POST',{invite_code:p.inv.invite_code,agent_name:'Imposter'})).status,409);assert.equal((await approve(p,other)).status,404);assert.equal((await req('/api/owner/pairings/'+p.pairing_id+'/approve','POST',{code:'BAD'},{owner})).status,422);});
test('approved exchange issues one hashed, scoped credential',async()=>{assert.equal((await approve(p)).status,200);const r=await redeem(p);assert.equal(r.status,200);token=r.body.access_token;cid=r.body.connection_id;assert.equal((await redeem(p)).status,409);assert.notEqual(sql.prepare('SELECT token_hash FROM connections WHERE id=?').get(cid).token_hash,token);assert.equal((await req('/api/v1/me')).status,401);assert.equal((await req('/api/v1/me','GET',undefined,{token})).status,200);});
test('profile sharing and optimistic revision checks',async()=>{const profile={expected_revision:0,interests:['tennis'],working_on:'API test',seeking:'',sharing_confirmed:true};assert.equal((await req('/api/v1/me/profile','PUT',{...profile,sharing_confirmed:false},{token})).status,422);assert.equal((await req('/api/v1/me/profile','PUT',profile,{token})).body.revision,1);assert.equal((await req('/api/v1/me/profile','PUT',profile,{token})).status,409);assert.equal((await req('/api/v1/me/profile','PUT',{...profile,expected_revision:1},{token})).body.revision,2);});
test('task nonce checked; duplicate replies stored exactly once',async()=>{task=(await req('/api/v1/me/tasks','GET',undefined,{token})).body.tasks[0];reply={client_message_id:'test-message-1',nonce:task.nonce,text:'Only harmless test data.'};assert.equal((await req('/api/v1/tasks/'+task.id+'/response','POST',{...reply,nonce:'wrong'},{token})).status,422);assert.equal((await req('/api/v1/tasks/'+task.id+'/response','POST',reply,{token})).status,201);const again=await req('/api/v1/tasks/'+task.id+'/response','POST',reply,{token});assert.equal(again.body.replayed,true);assert.equal(sql.prepare('SELECT count(*) AS n FROM responses WHERE task_id=?').get(task.id).n,1);assert.equal((await req('/api/v1/tasks/'+task.id+'/response','POST',{...reply,text:'Changed'},{token})).status,409);});
test('another owner and another connection cannot answer the task',async()=>{const q=await pair(other);await approve(q,other);const t=(await redeem(q)).body.access_token;assert.equal((await req('/api/v1/tasks/'+task.id+'/response','POST',reply,{token:t})).status,404);const room=(await req('/api/v1/room','GET',undefined,{token:t})).body;assert.equal(room.profiles.length,0);assert.equal(room.messages.length,0);assert.equal((await req('/api/owner/state','GET',undefined,{owner:other})).body.responses.length,0);});
test('delayed work stays unavailable until its release time',async()=>{const r=await req('/api/owner/tasks','POST',{connection_id:cid,prompt:'A later question',delay_seconds:300},{owner});assert.equal(r.status,201);assert.equal((await req('/api/v1/me/tasks','GET',undefined,{token})).body.tasks.length,0);assert.equal((await req('/api/v1/tasks/'+r.body.id+'/response','POST',{client_message_id:'late',nonce:r.body.nonce,text:'Answer'},{token})).status,409);sql.prepare('UPDATE tasks SET available_at=? WHERE id=?').run(Date.now()-1,r.body.id);assert.equal((await req('/api/v1/me/tasks','GET',undefined,{token})).body.tasks.length,1);assert.equal((await req('/api/v1/tasks/'+r.body.id+'/response','POST',{client_message_id:'late',nonce:r.body.nonce,text:'Answer'},{token})).status,201);});
test('data survives database close and reopen',async()=>{sql.close();sql=new DatabaseSync(join(dir,'db.sqlite'));sql.exec('PRAGMA foreign_keys=ON');const s=(await req('/api/owner/state','GET',undefined,{owner})).body;assert.equal(s.profiles[0].revision,2);assert.equal(s.responses.length,2);});
test('expired invites and tasks reject use',async()=>{const q=await pair();sql.prepare('UPDATE pairings SET expires_at=0 WHERE id=?').run(q.pairing_id);assert.equal((await approve(q)).status,410);const r=(await req('/api/owner/tasks','POST',{connection_id:cid,prompt:'Expiring task'},{owner})).body;sql.prepare('UPDATE tasks SET expires_at=0 WHERE id=?').run(r.id);assert.equal((await req('/api/v1/tasks/'+r.id+'/response','POST',{client_message_id:'expired',nonce:r.nonce,text:'Answer'},{token})).status,410);});
test('owner can replace a credential; old token dies and replacement stays private',async()=>{
 const path='/api/owner/connections/'+cid+'/token';
 assert.equal((await req(path,'POST',{})).status,401);
 assert.equal((await req(path,'POST',{},{owner:other})).status,404);
 assert.equal((await req(path,'POST',{},{owner,origin:'https://evil.test'})).status,403);
 const r=await req(path,'POST',{},{owner});assert.equal(r.status,200);
 assert.equal((await req('/api/v1/me','GET',undefined,{token})).status,401);
 token=r.body.access_token;assert.match(token,/^cr_[a-f0-9]{64}$/);
 assert.equal((await req('/api/v1/me','GET',undefined,{token})).status,200);
 assert.notEqual(sql.prepare('SELECT token_hash FROM connections WHERE id=?').get(cid).token_hash,token);
 assert.ok(!JSON.stringify((await req('/api/owner/state','GET',undefined,{owner})).body).includes(token));
});
test('revocation immediately denies access and cancels pending work',async()=>{await req('/api/owner/tasks','POST',{connection_id:cid,prompt:'Never answer this after revoke'},{owner});assert.equal((await req('/api/owner/connections/'+cid,'DELETE',undefined,{owner:other})).status,404);assert.equal((await req('/api/owner/connections/'+cid,'DELETE',undefined,{owner})).status,200);assert.equal((await req('/api/v1/me/tasks','GET',undefined,{token})).status,401);assert.equal((await req('/api/owner/connections/'+cid+'/token','POST',{},{owner})).status,404);assert.equal((await req('/api/v1/me/profile','PUT',{},{token})).status,401);assert.equal(sql.prepare("SELECT count(*) AS n FROM tasks WHERE connection_id=? AND status='pending'").get(cid).n,0);});
test('pre-authorized invite skips approval; manual approval stays the default',async()=>{
 const inv=await req('/api/owner/invites','POST',{auto_approve:true},{owner});
 assert.equal(inv.status,201);assert.equal(inv.body.auto_approve,true);
 const start=await req('/api/v1/pairings/start','POST',{invite_code:inv.body.invite_code,agent_name:'Auto Muse'});
 assert.equal(start.status,201);assert.equal(start.body.auto_approved,true);
 const issued=await redeem(start.body);
 assert.equal(issued.status,200);assert.match(issued.body.access_token,/^cr_[a-f0-9]{64}$/);
 assert.equal((await req('/api/v1/me','GET',undefined,{token:issued.body.access_token})).status,200);
 assert.equal((await req('/api/owner/pairings/'+start.body.pairing_id+'/approve','POST',{code:start.body.verification_code},{owner})).status,409);
 const plain=await req('/api/owner/invites','POST',{},{owner});
 assert.equal(plain.body.auto_approve,false);
 const manual=await req('/api/v1/pairings/start','POST',{invite_code:plain.body.invite_code,agent_name:'Manual Muse'});
 assert.equal(manual.body.auto_approved,false);
 assert.equal((await redeem(manual.body)).status,202);
 assert.equal((await req('/api/owner/invites','POST',{auto_approve:'yes'},{owner})).status,422);
});
test('health and unknown routes are bounded',async()=>{assert.equal((await req('/api/health')).status,200);assert.equal((await req('/api/v1/unknown')).status,401);sql.close();rmSync(dir,{recursive:true,force:true});});
