import {sqliteTable,text,integer,index,uniqueIndex} from 'drizzle-orm/sqlite-core';
// Each owner hosts one room (owner_id). Other owners join through room_invites and appear in room_members.
export const rooms=sqliteTable('rooms',{id:text('id').primaryKey(),ownerId:text('owner_id').notNull().unique(),createdAt:integer('created_at').notNull(),name:text('name')});
export const roomMembers=sqliteTable('room_members',{id:text('id').primaryKey(),roomId:text('room_id').notNull().references(()=>rooms.id),ownerId:text('owner_id').notNull(),ownerName:text('owner_name').notNull(),role:text('role').notNull(),joinedAt:integer('joined_at').notNull()},t=>[uniqueIndex('room_members_room_owner').on(t.roomId,t.ownerId),index('room_members_owner').on(t.ownerId)]);
// Only the SHA-256 of an invite code is stored; the code is shown to the host once.
export const roomInvites=sqliteTable('room_invites',{id:text('id').primaryKey(),roomId:text('room_id').notNull().references(()=>rooms.id),codeHash:text('code_hash').notNull().unique(),label:text('label'),createdBy:text('created_by').notNull(),createdAt:integer('created_at').notNull(),expiresAt:integer('expires_at').notNull(),maxUses:integer('max_uses').notNull(),uses:integer('uses').notNull().default(0),revokedAt:integer('revoked_at')},t=>[index('room_invites_room').on(t.roomId)]);
export const pairings=sqliteTable('pairings',{id:text('id').primaryKey(),roomId:text('room_id').notNull().references(()=>rooms.id),ownerId:text('owner_id').notNull(),inviteHash:text('invite_hash').notNull().unique(),deviceHash:text('device_hash'),code:text('code'),name:text('name'),status:text('status').notNull(),createdAt:integer('created_at').notNull(),expiresAt:integer('expires_at').notNull(),connectionId:text('connection_id'),autoApprove:integer('auto_approve').notNull().default(0)},t=>[index('pairings_owner').on(t.ownerId)]);
// source: 'connector' (owner-issued key) or 'pairing'. first_used_at marks the first authenticated request;
// last_inbox_at only moves on GET /api/v1/me/tasks, so ordinary API use is not mistaken for polling.
export const connections=sqliteTable('connections',{id:text('id').primaryKey(),ownerId:text('owner_id').notNull(),roomId:text('room_id').notNull().references(()=>rooms.id),name:text('name').notNull(),tokenHash:text('token_hash').notNull().unique(),createdAt:integer('created_at').notNull(),expiresAt:integer('expires_at').notNull(),revokedAt:integer('revoked_at'),lastSeenAt:integer('last_seen_at'),source:text('source').notNull().default('pairing'),firstUsedAt:integer('first_used_at'),lastInboxAt:integer('last_inbox_at'),lastReplyAt:integer('last_reply_at'),keyIssuedAt:integer('key_issued_at')},t=>[index('connections_room').on(t.roomId)]);
export const profiles=sqliteTable('profiles',{connectionId:text('connection_id').primaryKey().references(()=>connections.id),profileJson:text('profile_json').notNull(),revision:integer('revision').notNull(),updatedAt:integer('updated_at').notNull()});
// fetched_at records when the agent first received the task, separate from queued (created_at) and answered (completed_at).
export const tasks=sqliteTable('tasks',{id:text('id').primaryKey(),roomId:text('room_id').notNull().references(()=>rooms.id),connectionId:text('connection_id').notNull().references(()=>connections.id),prompt:text('prompt').notNull(),nonce:text('nonce').notNull(),kind:text('kind').notNull(),status:text('status').notNull(),createdAt:integer('created_at').notNull(),availableAt:integer('available_at').notNull(),expiresAt:integer('expires_at').notNull(),completedAt:integer('completed_at'),fetchedAt:integer('fetched_at'),roundId:text('round_id')},t=>[index('tasks_inbox').on(t.connectionId,t.status,t.availableAt)]);
export const responses=sqliteTable('responses',{id:text('id').primaryKey(),roomId:text('room_id').notNull(),taskId:text('task_id').notNull().unique().references(()=>tasks.id),connectionId:text('connection_id').notNull(),clientId:text('client_id').notNull(),text:text('text').notNull(),nonce:text('nonce').notNull(),createdAt:integer('created_at').notNull()},t=>[uniqueIndex('responses_client').on(t.connectionId,t.clientId)]);
// Recorded activity: connected, inbox_check, tasks_fetched, reply_posted, profile_updated, key_issued, key_replaced, revoked, round_queued.
export const events=sqliteTable('events',{id:text('id').primaryKey(),roomId:text('room_id').notNull(),connectionId:text('connection_id'),type:text('type').notNull(),detail:text('detail'),createdAt:integer('created_at').notNull()},t=>[index('events_room').on(t.roomId,t.createdAt),index('events_connection').on(t.connectionId,t.type,t.createdAt)]);
// Standalone owner accounts, used when the app is not hosted behind Sites sign-in.
export const owners=sqliteTable('owners',{id:text('id').primaryKey(),email:text('email').notNull().unique(),name:text('name').notNull(),passwordHash:text('password_hash').notNull(),passwordSalt:text('password_salt').notNull(),createdAt:integer('created_at').notNull(),failedLogins:integer('failed_logins').notNull().default(0),lockedUntil:integer('locked_until')});
export const sessions=sqliteTable('sessions',{idHash:text('id_hash').primaryKey(),ownerId:text('owner_id').notNull().references(()=>owners.id),createdAt:integer('created_at').notNull(),expiresAt:integer('expires_at').notNull()},t=>[index('sessions_owner').on(t.ownerId)]);
