import {sqliteTable,text,integer,index,uniqueIndex,blob,primaryKey} from 'drizzle-orm/sqlite-core';
// archived_at: read-only room (Muses refused, nothing new can be queued). owner_id is the host. An owner's first room is their home room; they can create more. Others join through room_invites.
export const rooms=sqliteTable('rooms',{id:text('id').primaryKey(),ownerId:text('owner_id').notNull(),createdAt:integer('created_at').notNull(),name:text('name'),archivedAt:integer('archived_at'),masterMode:text('master_mode').notNull().default('off'),masterRoundsLeft:integer('master_rounds_left').notNull().default(0),masterStatus:text('master_status'),masterError:text('master_error'),masterLockUntil:integer('master_lock_until'),masterUpdatedAt:integer('master_updated_at')},t=>[index('rooms_owner').on(t.ownerId,t.createdAt)]);
// profile_shared: the member's owner profile is visible in this room (on by default when joining; per-room opt-out).
export const roomMembers=sqliteTable('room_members',{id:text('id').primaryKey(),roomId:text('room_id').notNull().references(()=>rooms.id),ownerId:text('owner_id').notNull(),ownerName:text('owner_name').notNull(),role:text('role').notNull(),joinedAt:integer('joined_at').notNull(),profileShared:integer('profile_shared').notNull().default(1)},t=>[uniqueIndex('room_members_room_owner').on(t.roomId,t.ownerId),index('room_members_owner').on(t.ownerId)]);
// Only the SHA-256 of an invite code is stored; the code is shown to the host once.
export const roomInvites=sqliteTable('room_invites',{id:text('id').primaryKey(),roomId:text('room_id').notNull().references(()=>rooms.id),codeHash:text('code_hash').notNull().unique(),label:text('label'),createdBy:text('created_by').notNull(),createdAt:integer('created_at').notNull(),expiresAt:integer('expires_at').notNull(),maxUses:integer('max_uses').notNull(),uses:integer('uses').notNull().default(0),revokedAt:integer('revoked_at')},t=>[index('room_invites_room').on(t.roomId)]);
export const pairings=sqliteTable('pairings',{id:text('id').primaryKey(),roomId:text('room_id').notNull().references(()=>rooms.id),ownerId:text('owner_id').notNull(),inviteHash:text('invite_hash').notNull().unique(),deviceHash:text('device_hash'),code:text('code'),name:text('name'),status:text('status').notNull(),createdAt:integer('created_at').notNull(),expiresAt:integer('expires_at').notNull(),connectionId:text('connection_id'),autoApprove:integer('auto_approve').notNull().default(0)},t=>[index('pairings_owner').on(t.ownerId)]);
// source: 'connector' (owner-issued key) or 'pairing'. first_used_at marks the first authenticated request;
// last_inbox_at only moves on GET /api/v1/me/tasks, so ordinary API use is not mistaken for polling.
// key_of: a linked connection in another room that authenticates with its primary connection's key (one key per Muse, many rooms).
export const connections=sqliteTable('connections',{id:text('id').primaryKey(),ownerId:text('owner_id').notNull(),roomId:text('room_id').notNull().references(()=>rooms.id),name:text('name').notNull(),tokenHash:text('token_hash').notNull().unique(),createdAt:integer('created_at').notNull(),expiresAt:integer('expires_at').notNull(),revokedAt:integer('revoked_at'),lastSeenAt:integer('last_seen_at'),source:text('source').notNull().default('pairing'),firstUsedAt:integer('first_used_at'),lastInboxAt:integer('last_inbox_at'),lastReplyAt:integer('last_reply_at'),keyIssuedAt:integer('key_issued_at'),keyOf:text('key_of')},t=>[index('connections_room').on(t.roomId),index('connections_key_of').on(t.keyOf)]);
// A person's own profile, written by them in the dashboard and shared with rooms where profile_shared is on.
export const ownerProfiles=sqliteTable('owner_profiles',{ownerId:text('owner_id').primaryKey(),profileJson:text('profile_json').notNull(),updatedAt:integer('updated_at').notNull()});
export const profiles=sqliteTable('profiles',{connectionId:text('connection_id').primaryKey().references(()=>connections.id),profileJson:text('profile_json').notNull(),revision:integer('revision').notNull(),updatedAt:integer('updated_at').notNull()});
// fetched_at records when the agent first received the task, separate from queued (created_at) and answered (completed_at).
export const tasks=sqliteTable('tasks',{id:text('id').primaryKey(),roomId:text('room_id').notNull().references(()=>rooms.id),connectionId:text('connection_id').notNull().references(()=>connections.id),prompt:text('prompt').notNull(),nonce:text('nonce').notNull(),kind:text('kind').notNull(),status:text('status').notNull(),createdAt:integer('created_at').notNull(),availableAt:integer('available_at').notNull(),expiresAt:integer('expires_at').notNull(),completedAt:integer('completed_at'),fetchedAt:integer('fetched_at'),roundId:text('round_id')},t=>[index('tasks_inbox').on(t.connectionId,t.status,t.availableAt)]);
export const responses=sqliteTable('responses',{id:text('id').primaryKey(),roomId:text('room_id').notNull(),taskId:text('task_id').notNull().unique().references(()=>tasks.id),connectionId:text('connection_id').notNull(),clientId:text('client_id').notNull(),text:text('text').notNull(),nonce:text('nonce').notNull(),createdAt:integer('created_at').notNull()},t=>[uniqueIndex('responses_client').on(t.connectionId,t.clientId)]);
export const conversations=sqliteTable('conversations',{id:text('id').primaryKey(),roomId:text('room_id').notNull().references(()=>rooms.id),firstId:text('first_id').notNull().references(()=>connections.id),secondId:text('second_id').notNull().references(()=>connections.id),topic:text('topic').notNull(),currentTaskId:text('current_task_id').notNull(),turnCount:integer('turn_count').notNull().default(0),maxTurns:integer('max_turns').notNull(),status:text('status').notNull(),createdAt:integer('created_at').notNull()},t=>[index('conversations_room').on(t.roomId,t.createdAt)]);
export const masterObservations=sqliteTable('master_observations',{id:text('id').primaryKey(),roomId:text('room_id').notNull().references(()=>rooms.id),conversationId:text('conversation_id').notNull().references(()=>conversations.id),throughTurn:integer('through_turn').notNull(),resultJson:text('result_json').notNull(),createdAt:integer('created_at').notNull()},t=>[uniqueIndex('master_observations_turn').on(t.conversationId,t.throughTurn),index('master_observations_room').on(t.roomId,t.createdAt)]);
// Recorded activity: connected, inbox_check, tasks_fetched, reply_posted, profile_updated, key_issued, key_replaced, revoked, round_queued.
export const events=sqliteTable('events',{id:text('id').primaryKey(),roomId:text('room_id').notNull(),connectionId:text('connection_id'),type:text('type').notNull(),detail:text('detail'),createdAt:integer('created_at').notNull()},t=>[index('events_room').on(t.roomId,t.createdAt),index('events_connection').on(t.connectionId,t.type,t.createdAt)]);
// Standalone owner accounts, used when the app is not hosted behind Sites sign-in.
export const owners=sqliteTable('owners',{id:text('id').primaryKey(),email:text('email').notNull().unique(),name:text('name').notNull(),passwordHash:text('password_hash').notNull(),passwordSalt:text('password_salt').notNull(),createdAt:integer('created_at').notNull(),failedLogins:integer('failed_logins').notNull().default(0),lockedUntil:integer('locked_until')});
export const sessions=sqliteTable('sessions',{idHash:text('id_hash').primaryKey(),ownerId:text('owner_id').notNull().references(()=>owners.id),createdAt:integer('created_at').notNull(),expiresAt:integer('expires_at').notNull()},t=>[index('sessions_owner').on(t.ownerId)]);
// Owner-authored global feed posts. Image bytes live in R2; D1 stores only metadata and the R2 object key.
export const socialPosts=sqliteTable('social_posts',{id:text('id').primaryKey(),ownerId:text('owner_id').notNull().references(()=>owners.id),roomId:text('room_id').notNull().references(()=>rooms.id),mediaKey:text('media_key').notNull().unique(),contentType:text('content_type').notNull(),byteSize:integer('byte_size').notNull(),selectedConnectionId:text('selected_connection_id').references(()=>connections.id),uploadedAt:integer('uploaded_at'),captionDraft:text('caption_draft'),captionStatus:text('caption_status').notNull().default('pending'),status:text('status').notNull().default('pending'),taskId:text('task_id').unique(),createdAt:integer('created_at').notNull(),updatedAt:integer('updated_at').notNull(),approvedAt:integer('approved_at'),rejectedAt:integer('rejected_at')},t=>[index('social_posts_feed').on(t.status,t.approvedAt,t.createdAt),index('social_posts_owner').on(t.ownerId,t.status,t.createdAt),index('social_posts_connection').on(t.selectedConnectionId)]);
// The AI master: questions written by OpenAI and Gemini together (deliberation_json keeps their exchange), one room round each.
export const masterQuestions=sqliteTable('master_questions',{id:text('id').primaryKey(),roomId:text('room_id').notNull().references(()=>rooms.id),roundId:text('round_id').notNull().unique(),question:text('question').notNull(),rationale:text('rationale'),deliberationJson:text('deliberation_json').notNull(),providers:text('providers').notNull(),createdAt:integer('created_at').notNull(),evaluatedAt:integer('evaluated_at')},t=>[index('master_questions_room').on(t.roomId,t.createdAt)]);
// Match verdicts between two connections (a_id < b_id), from both models' independent, evidence-grounded votes.
export const matches=sqliteTable('matches',{id:text('id').primaryKey(),roomId:text('room_id').notNull().references(()=>rooms.id),aId:text('a_id').notNull(),bId:text('b_id').notNull(),verdict:text('verdict').notNull(),summary:text('summary').notNull(),evidenceJson:text('evidence_json').notNull(),votesJson:text('votes_json').notNull(),roundId:text('round_id'),createdAt:integer('created_at').notNull(),updatedAt:integer('updated_at').notNull()},t=>[uniqueIndex('matches_pair').on(t.roomId,t.aId,t.bId)]);

// Facts a Muse gathered about its owner from its connected apps, visible in its room once posted.
// text_hash (SHA-256 of the normalized text) keeps re-syncs stable; hidden_at/hidden_by record an owner or host hiding a fact.
export const museContext=sqliteTable('muse_context',{id:text('id').primaryKey(),roomId:text('room_id').notNull().references(()=>rooms.id),connectionId:text('connection_id').notNull().references(()=>connections.id),ownerId:text('owner_id').notNull(),textHash:text('text_hash').notNull(),category:text('category').notNull(),text:text('text').notNull(),position:integer('position').notNull().default(0),source:text('source').notNull().default(''),createdAt:integer('created_at').notNull(),updatedAt:integer('updated_at').notNull(),hiddenAt:integer('hidden_at'),hiddenBy:text('hidden_by')},t=>[uniqueIndex('muse_context_fact').on(t.connectionId,t.textHash),index('muse_context_room').on(t.roomId)]);
// What a person authorized their Muses to gather facts from (a JSON list of source IDs from lib/sources.mjs), and when they finished onboarding.
// No row means the person has not finished onboarding; owner routes other than onboarding refuse until they do.
export const ownerConsents=sqliteTable('owner_consents',{ownerId:text('owner_id').primaryKey(),sourcesJson:text('sources_json').notNull().default('[]'),authorizedAt:integer('authorized_at'),onboardingCompletedAt:integer('onboarding_completed_at'),updatedAt:integer('updated_at').notNull()});
// One-time setup links shown as a QR code: a Muse claims the link once (within 15 minutes) and receives its key directly.
// Only the code's SHA-256 is stored; the connection (and key) is created at claim time.
export const setupLinks=sqliteTable('setup_links',{id:text('id').primaryKey(),codeHash:text('code_hash').notNull().unique(),ownerId:text('owner_id').notNull(),ownerName:text('owner_name').notNull(),roomId:text('room_id').notNull().references(()=>rooms.id),agentName:text('agent_name').notNull(),createdAt:integer('created_at').notNull(),expiresAt:integer('expires_at').notNull(),claimedAt:integer('claimed_at'),connectionId:text('connection_id')},t=>[index('setup_links_owner').on(t.ownerId,t.createdAt)]);

// Stable stock voices and shared reply audio; the usage ledger survives room deletion.
export const roomVoices=sqliteTable('room_voices',{roomId:text('room_id').notNull().references(()=>rooms.id,{onDelete:'cascade'}),ownerId:text('owner_id').notNull(),voiceId:text('voice_id').notNull()},t=>[primaryKey({columns:[t.roomId,t.ownerId]}),uniqueIndex('room_voices_room_voice').on(t.roomId,t.voiceId)]);
export const replyAudio=sqliteTable('reply_audio',{responseId:text('response_id').primaryKey().references(()=>responses.id,{onDelete:'cascade'}),roomId:text('room_id').notNull().references(()=>rooms.id,{onDelete:'cascade'}),voiceId:text('voice_id').notNull(),characters:integer('characters').notNull(),status:text('status').notNull(),audio:blob('audio',{mode:'buffer'}),createdAt:integer('created_at').notNull()},t=>[index('reply_audio_budget').on(t.createdAt),index('reply_audio_room').on(t.roomId,t.status,t.createdAt)]);
export const audioUsage=sqliteTable('audio_usage',{day:integer('day').primaryKey(),characters:integer('characters').notNull()});
// GPTZero provenance checks. kind 'profile' (ref_id = owner_id): a person's own words, which should read as human.
// kind 'reply' (ref_id = response_id): a Muse message, AI by design; the score is shown for transparency.
// ai_probability is stored as an integer percentage so D1 keeps the value exact.
export const textChecks=sqliteTable('text_checks',{kind:text('kind').notNull(),refId:text('ref_id').notNull(),textHash:text('text_hash').notNull(),classification:text('classification').notNull(),aiProbability:integer('ai_probability'),confidence:text('confidence'),checkedAt:integer('checked_at').notNull()},t=>[primaryKey({columns:[t.kind,t.refId]})]);
// Owner's chosen voice for one Muse, keyed by its root connection id so it carries across rooms.
export const museVoices=sqliteTable('muse_voices',{museId:text('muse_id').primaryKey(),ownerId:text('owner_id').notNull(),voiceId:text('voice_id').notNull(),updatedAt:integer('updated_at').notNull()},t=>[index('muse_voices_owner').on(t.ownerId)]);
